name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, my name is Farmer Jer.  I build websites such as https://doghousetimes.com and https://farmerjer.com as well as https://boating.guide 
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

- name: Setup Dotnet for use with actions
  uses: actions/setup-dotnet@v1.0.0
  with:
    # Version to use. E.g. 2.2.104
    version: # optional
